package Exceptions;

public class Demo2 {
 
	public static void main(String[] args) {
		
		System.out.println("********************");
		
		int[] arr1 = new int[5];
		int i=12;
		int j=0;
		try{
			System.out.println("Running outter try block");
	          try{
	        	  
	        	  System.out.println("Running inner try block");
	 	         
	        	  j=i/0;
	          
	        System.out.println("Exiting inner try block");;
	          
		}
		catch(ArithmeticException e){
			System.out.println("Arithematic Exception");
		}
	          arr1[5]=45;
		}
		System.out.println("Exiting the outter try block");
			catch (ArrayIndexOutOfBoundsException e) {
				
			System.out.println("ArrayIndexOutOfBoundsException handled");
			}
		
		System.out.println("i value: "	+i);
		System.out.println("j value: "+j);
		System.out.println("Array elements");
		for(int j=0;j<arr1.lenght;j++){
			System.out.println(arr1[j]);
		}
		
		
		
		System.out.println("********************");
		
	}
	
}
